[[theme.fontFaces]]
family="noto-sans"
url="app/static/NotoSans-Italic-VariableFont_wdth,wght.ttf"
style="italic"
[[theme.fontFaces]]
family="noto-sans"
url="app/static/NotoSans-VariableFont_wdth,wght.ttf"
style="normal"
weight=400
[[theme.fontFaces]]
family="noto-sans"
url="app/static/NotoSans-VariableFont_wdth,wght.ttf"
style="bold"
weight=700
[[theme.fontFaces]]
family="dancing-script"
url="app/static/DancingScript-VariableFont_wght.ttf"
style="medium"
weight=500

[theme]
base = "light"
primaryColor="#6200EE"
backgroundColor="white"
secondaryBackgroundColor="#D1C4E9"
codeBackgroundColor="powderBlue"
baseRadius = "medium"
showWidgetBorder = true
baseFontSize = 11
font="noto-sans"
headingFont="dancing-script"
blueColor="#3700B3"

[theme.sidebar]
backgroundColor="ghostWhite"
secondaryBackgroundColor="lavender"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"