# Wedding Configuration
[wedding]
page_title = "Wedding RSVP Tracker"
page_icon = ":material/favorite:"
wedding_couple = "Robert & Charlotte"
banner_image = "https://cherylbarker.net/wp-content/uploads/2018/02/pexels-photo-256737-1024x681.jpeg"

# File Configuration
[files]
csv_file = "wedding_rsvps.csv"

# Admin Configuration
[admin]
password = "wedding2024"

# Menu Configuration
[menu]
starters = [
    "Ham Hock Terrine (GF)",
    "Deep Fried Camembert (V)",
    "Prawn Cocktail (GF available)"
]

starters_detailed = [
    "**Deep Fried Camembert** _with Cranberry Sauce and salad garnish (V)_",
    "**Ham Hock Terrine** _with gluten free bread, honey mustard dressing crispy salad and caramelised onions (GF)_",
    "**Prawn Cocktail** _with Marie Rose Sauce, tomatoes, baby gem lettuce, lemon and bread and butter (GF available)_"
]

mains = [
    "Braised and Confit Shoulder of Lamb (GF)",
    "Salmon en Papillote (GF)",
    "Wild Mushroom and Spinach Wellington (V/GF)"
]

mains_detailed = [
    "**Braised and confit shoulder of Lamb** _with dauphinoise potato, seasonal vegetables and bone marrow gravy (GF)_",
    "**Salmon en Papilotte** _with sliced baby potatoes and a white wine and cream dill sauce (GF)_",
    "**Wild Mushroom and Spinach Wellington** _with crushed potatoes, seasonal vegetables and gravy (V/GF)_",
    "Seasonal Vegetables served as side dish"
]

desserts = [
    "Lemon Cheesecake (V)",
    "Eton Mess (V/GF)",
    "Cheeseboard (V) (GF available)"
]

desserts_detailed = [
    "**Brule Lemon Cheesecake** _with a caramel torched top and raspberry sorbet (V)_",
    "**Eton Mess** _with fresh strawberries, meringue and cream (V/GF)_",
    "**Cheeseboard** _a selection of brie, goats cheese, stilton and smoked applewood with chutney, crackers and fruit (V) (GF available)_"
]
# RSVP Deadline Configuration
[deadline]
# RSVP deadline in YYYY-MM-DD HH:MM format (24-hour time)
deadline_datetime = "2025-12-01 23:59"
# Timezone (optional, defaults to local)
timezone = "Europe/London"
# Grace period in hours after deadline for admin override
grace_period_hours = 24
# Warning period in days before deadline to show urgency
warning_days = 7

# UI Configuration
[ui]
welcome_message = "We're excited to celebrate our special day with you! Please let us know if you'll be joining us."

# Event Information
[event]
welcome_text = "Join us as we celebrate our wedding day! Below you'll find all the details you need for our special celebration."

wedding_date = "Saturday, June 20th, 2026"
ceremony_time = "3:00 PM"

# Ceremony Venue (Church)
ceremony_venue_name = "St. Michael & All Angels Church"
ceremony_venue_address = "East End, Langtoft, PE6 9LP"
ceremony_venue_description = "A beautiful historic parish church dating back to the 13th century."
ceremony_venue_image = "https://nessgroup.org/wp-content/uploads/2020/07/start-service-8.jpg"
ceremony_venue_map_url = "https://maps.google.com/?q=St+Michael+and+All+Angels+Church+Langtoft"
# Optional: Add coordinates for interactive map
ceremony_venue_latitude = 52.69912743039774
ceremony_venue_longitude = -0.3388956776120908

# Reception Venue
venue_name = "The White Hart"
venue_address = "Main St, Ufford, Stamford, PE9 3BH, United Kingdom"
venue_description = "The White Hart is a coaching inn dating back to the 17th century close to the a historic town of Stamford, Lincolnshire."
venue_image = "https://www.realweddings.co.uk/detail/the-white-hart-ufford/m/v/showcase_hero/91652/459927009_18285199603224087_4291546012477049125_n.jpg"
venue_map_url = "https://maps.google.com/?q=The+White+Hart+Ufford+Woodbridge"
# Optional: Add coordinates for interactive map
venue_latitude = 52.62428115443177
venue_longitude = -0.38509257289760546

# Dress Code
dress_code = ""
dress_code_notes = ""

# Accommodations intro
accommodations_intro = "We have reserved room blocks at the following hotels for your convenience:"

# Gift Registry
registry_message = "Your presence at our wedding is the greatest gift we could ask for. However, if you wish to give something, we have registered at the following stores:"

# Timeline
[[event.timeline]]
time = "2:30 PM"
event = "Guest Arrival at Church"
description = "Please arrive at St. Michael and All Angels Church for the ceremony"

[[event.timeline]]
time = "3:00 PM"
event = "Wedding Ceremony"
description = "The ceremony will take place at St. Michael and All Angels Church"

[[event.timeline]]
time = "4:15 PM"
event = "Drinks Reception at The White Hart"
description = "Join us for champagne and canapés in the gardens"

[[event.timeline]]
time = "4.45 PM"
event = "Bride and Groom Arrive"
description = "The newlyweds will arrive at The White Hart"

[[event.timeline]]
time = "6:00 PM"
event = "Wedding Breakfast"
description = "Three-course meal at The White Hart"

[[event.timeline]]
time = "8:15 PM"
event = "Speeches & Cake Cutting"

[[event.timeline]]
time = "8:30 PM"
event = "First Dance & Evening Reception"
description = "Entertainment until 11:00 PM"

[[event.timeline]]
time = "11:00 PM"
event = "Carriages"

# Accommodations
accommodations_intro = "We have reserved room blocks at the following hotels for your convenience:"

[[event.accommodations]]
name = "The White Hart (Venue Hotel)"
address = "Main St, Ufford, Stamford, PE9 3BH, United Kingdom"
distance = "At the venue"
phone = "+44 1780 740250"
booking_code = "ROBERT-CHARLOTTE-2026"
website = "https://www.whitehartufford.co.uk"
notes = "Limited rooms available - book early! Mention the wedding when booking."

# Transportation
[event.transportation]
parking = "Free parking is available at the venue."
public_transport = "The nearest train station is Stamford (approximately 5.5 miles away). Taxis are available from the station to the venue."
taxi_info = "We recommend booking taxis in advance. Local taxi services include Ace Cabs of Stamford (+44 1780 767676) and ABC Taxis (+44 1780 252525)."

# Gift Registry
[[event.registry]]
name = ""
url = ""

[[event.registry]]
name = ""
url = ""

[[event.registry]]
name = ""
url = ""

# Additional Information
[[event.additional_info]]
title = ""
content = "We love your little ones, but we've decided to make our wedding an adults-only celebration. We hope this gives you a chance to relax and enjoy the evening!"

[[event.additional_info]]
title = "Photography & Videography"
content = "We have a professional photographer and videographer capturing our special day. Feel free to take photos, but we kindly ask for an unplugged ceremony - please put away phones and cameras during the ceremony itself."

[[event.additional_info]]
title = "Dietary Requirements"
content = "Please let us know about any dietary requirements or allergies when completing your RSVP. Our caterers can accommodate most dietary needs including vegetarian, vegan, gluten-free, and other requirements."

[[event.additional_info]]
title = "Gift Policy"
content = "Please do not feel obliged to bring gifts. Your presence is truly the best present. If you do wish to give something you can contribute to our honeymoon fund."

# Contact Information
[event.contact.bride]
name = "Charlotte"
email = "cxganderton@gmail.com"
phone = "+44 7941 105494"

[event.contact.groom]
name = "Robert"
email = "robert.castley@gmail.com"
phone = "+44 7918 035577"